### Register
POST {{host}}/api/register
Content-Type: application/json

{
    "email": "{{email}}",
    "password": "{{password}}",
    "first_name": "Jan",
    "last_name": "Novák"
}


### Login
POST {{host}}/api/login
Content-Type: application/json

{
    "email": "{{email}}",
    "password": "{{password}}"
}
