@table = items
@foreignKey1 = group_id
@foreignKey1Value = 5
@foreignKey2 = group_id
@foreignKey2Value = 7
@tableId = 36

###
GET {{host}}/api/{{table}}
Content-Type: application/json
Authorization: Bearer {{token}}

{   
}

###

GET {{host}}/api/{{table}}
X-Pagination-Limit: 2
X-Pagination-Offset: 3
X-Sort-By: created_at
X-Sort-Direction: ASC
Authorization: Bearer {{token}}

{
}

###
GET {{host}}/api/{{table}}/{{tableId}}
Content-Type: application/json
Authorization: Bearer {{token}}

{
}

###
GET {{host}}/api/{{table}}/search?search=zk204
Content-Type: application/json
Authorization: Bearer {{token}}

{
}

###
GET {{host}}/api/items/options
Content-Type: application/json
Authorization: Bearer {{token}}

{
}

###
GET {{host}}/api/{{table}}/options
Content-Type: application/json
Authorization: Bearer {{token}}

{
}


###
POST {{host}}/api/{{table}}
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name": "Peklo",
    "description": "Příliš žluťoučký kůň úpěl ďábelské ódy.",
    "gps_lat": "49.2251697",
    "gps_lon": "17.6656944"
}

###
PUT {{host}}/api/{{table}}/{{tableId}}
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name": "Peklíčko"
}


###
DELETE {{host}}/api/{{table}}/{{tableId}}
Content-Type: application/json
Authorization: Bearer {{token}}

{
}

###
GET {{host}}/api/{{table}}?foreignKeys=true&{{foreignKey1}}={{foreignKey1Value}}&{{foreignKey2}}={{foreignKey2Value}}
Content-Type: application/json
Authorization: Bearer {{token}}

{   
}