POST http://splk2.test/api/register
Content-Type: application/json

#test1234
{
    "email": "novy_uzivatel@test.cz",
    "password": "$2y$10$IL793KhtLhjlQbP6WG61r.nOeoy9tDDPX9.UTJXas8C3gnXzngV5.",
    "first_name": "Jan",
    "last_name": "Novák"
}
