GET {{host}}/api/schema
Content-Type: application/json
Authorization: Bearer {{token}}

{
}

###
GET {{host}}/api/schema/groups
Content-Type: application/json
Authorization: Bearer {{token}}

{
}

###
GET {{host}}/api/schema/loans
Content-Type: application/json
Authorization: Bearer {{token}}

{
}
